<?
$aMenuLinks = Array(
    Array(
        "Доставка",
        "/dostavka/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Оплата",
        "/oplata/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Клиенты",
        "/o-kompanii/clients/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Для дилеров",
        "/informacziya-dlya-dilerov/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Разработка сувенирной продукции",
        "/informacziya-dlya-dilerov/razrabotka-suvenirnoj-produkcii.php",
        Array(),
        Array(),
        ""
    )
);
?>