<?
$aMenuLinks = Array(
	Array(
		"Новости и статьи",
		"/novosti/",
		Array(), 
		Array(), 
		"" 
	),
    Array(
        "Сотрудники",
        "/o-kompanii/sotrudniki/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вакансии",
        "/o-kompanii/vakansii.php",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Обратная связь",
        "/o-kompanii/feedback/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Портфолио",
        "/o-kompanii/clients/",
        Array(),
        Array(),
        ""
    )
);
?>